# Generated by Django 5.1.7 on 2025-03-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
